### ISSUE TITLE
[Feature Request] Multiple Feature Request

### ISSUE THREAD

**Issue by joyskmathew** [FireCubeStudios/UnitedSets#22]
Hi, 

Can i request two essential features for productivity:
1. **Ability to rename the tab** 
2. **Ability to cycle through the tab using keyboard shortcuts.**

**Comment by Get0457** [comment]
> Ability to rename the tab
I already implemented this but did not release it on the store version yet. (If you want to, you can clone from source and try it out)

> Ability to cycle through the tab using keyboard shortcuts.
I'll answer this in terms of general keyboard shortcuts since they all have the same issue.

Unfortunately, it might be hard to impossible to implement shortcuts in general since you are focusing in other programs, not on United Sets. One idea is to implement as global hotkeys, but this will influence how other program works.

For example, if I implement `Ctrl + W` shortcut to close the tab, if you use Browser (like Google Chrome or Microsoft Edge or other apps with tabs), it will close the tab on both United Sets and the browser, which causes weird behavior.

If I implement `Ctrl + Tab` shortcut to switch tab, if you use Browser, it will switch the tab on both United Sets and the browser, which causes weird behavior.

With these reasons in mind, I have no idea how to implement this to provide a good user experience. Pull Requests about this will be accepted if it will not have side effects on other software.

**Comment by FireCubeStudios** [comment]
For our shortcuts we should do ctrl shift instead of just ctrl

**Comment by Get0457** [comment]
`Ctrl + Shift + Tab` is universally used with many apps with tabs, as `Ctrl + Tab` but going in the opposite direction so this is not going to work

**Comment by JashanveerS** [comment]
Or we can edit our own shortcuts, that would be awesome

**Comment by Get0457** [comment]
I will close this issue for now. Tab Switcher will be tracked on #23
