### ISSUE TITLE
[Bug] Add exception for Windows classes

### ISSUE THREAD

**Issue by rocksdanister** [FireCubeStudios/UnitedSets#8]
- Holding tab and clicking on desktop will adds Progman
- Holding tab and clicking on taskbar adds it
- Holding tab and clicking on Sets settings window will adds it (WinUI desktop)

<img width="659" alt="image" src="https://user-images.githubusercontent.com/17554161/197217312-6221f47c-73c3-4618-acd3-0dcf1677095d.png">

**Comment by FireCubeStudios** [comment]
Good idea. This will be easy to add

**Comment by Get0457** [comment]
Exception Added
`Shell_TrayWnd` // Taskbar
`Progman` // Desktop
`Chrome_WidgetWin_1` // I don't know why but I also see this on desktop
`WindowsDashboard` // Widget
`Windows.UI.Core.CoreWindow` // Quick Settings and Notification Center (other UWP apps should already be `ApplicationFrameHost`)

The changes is in [this commit](https://github.com/FireCubeStudios/UnitedSets/commit/7fbd6cc93ea6d1692f64a55293bba5777e548680). The next app update should fix the problem or you can clone from source to get the latest development version.

**Comment by Get0457** [comment]
Also, although it is not mentioned in this issue, please note that if you have modern systray apps with Xaml flyouts that are not part of Windows itself (such as EarTrumpet, and ModernFlyouts) will not be fixed because it is not really possible to fix all of them. The best way for these modern systray apps is... don't add them.

**Comment by Get0457** [comment]
Now available for Experimental InDev Version, link in Readme
